In [1]:
import pandas

In [2]:
ds= pandas.read_csv('Salary_Data.csv')

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [22]:
ds.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [12]:
x= ds['YearsExperience'].values.reshape(30,1)

In [8]:
y = ds['Salary']

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
model= LinearRegression()

In [13]:
model.fit(x,y)

LinearRegression()

In [14]:
model.coef_


array([9449.96232146])

In [15]:
model.intercept_

25792.20019866871

In [16]:
model.predict([[2.2]])

array([46582.11730587])

In [17]:
import joblib

In [18]:
joblib.dump(model, 'salary.pk1')

['salary.pk1']

In [19]:
joblib.load('salary.pk1')

LinearRegression()

In [20]:
model.predict([[3.4]])

array([57922.07209162])